### ISSUE TITLE
Forgot Password - email never received

### ISSUE THREAD

**Issue by william-liebenberg** [SSWConsulting/SSW.SugarLearning#17]
Hi all

I tried using Forgot password link, because... I can't remember my password :)

Never received any emails from SL to change my password :(

**Comment by christoment** [comment]
We have a new forgot password page, but the link provided in the email is not working at the moment. Tracking this bug in AB#55246 .

Fixing this bug should unblock this issue with the new forgot password page.

**Comment by christoment** [comment]
Clicking Forgot password should now work and will send an email containing the link to reset the password.

@william-liebenberg you should now be unblocked to forgot your password .

- Chris

**Comment by christoment** [comment]
I found out that we haven't set up Domain Authentication yet on our SMTP. Re-opening this issue in case it is blocking outlook.com to receive email from SugarLearning.

**Comment by christoment** [comment]
Hi @william-liebenberg ,

Done - I just checked today and SugarLearning can now send emails again to outlook.com.

More detail:
Nothing has been done on our end apart from adding the Domain Authentication on our SMTP provider.

I got in touch with our provider and they said that although they can't manually move us to another IP pool, they have an automated system that will move sender with high reputation to another IP pool with high reputation 
as well.
And since we have high reputation and domain authentication set up, looks like their system has moved us to another IP pool.

- Chris
